[project]
name = "water-pi-api"
version = "0.1.0"
description = "A lightweight API to control the water treatment center."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "flask>=3.1.2",
    "gunicorn>=25.1.0",
]
