[project]
name = "nuclear-api"
version = "0.1.0"
description = "lightweight API to control nuclear smokestacks"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "flask>=3.1.3",
    "gpiozero>=2.0.1",
    "gunicorn>=25.1.0",
]
